
FROM python:3.9-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk add --no-cache \
        gcc \
        g++ \
        musl-dev \
        python3-dev \
        libffi-dev 

COPY ./csrf/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./csrf .

COPY ./csrf/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
RUN sed -i 's/\r//' /docker-entrypoint.sh
EXPOSE 8000
ENTRYPOINT ["/docker-entrypoint.sh"]