services:
  flask:
    build:
      context: .
      dockerfile: ./xss/Dockerfile
    restart: unless-stopped
    
    expose:
      - "8000"
    networks:
      - lab_net
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maximum size of each log file (e.g., 10 megabytes)
        max-file: "3"  # Maximum number of log files to keep

  xss:
    image: vladimirjk/haproxy-docker-logs:1.8-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
      - "8404:8404"
    volumes:
      - ./xss/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - flask
    networks:
      - lab_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maximum size of each log file (e.g., 10 megabytes)
        max-file: "3"  # Maximum number of log files to keep

  csrf:
    build:
      context: .
      dockerfile: ./csrf/dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "127.0.0.1:81:80"
    networks:
      - lab_net

    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maximum size of each log file (e.g., 10 megabytes)
        max-file: "3"  # Maximum number of log files to keep
  clickjacking:
    build:
      context: clickjacking
      dockerfile: ./dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "127.0.0.1:82:443"
    networks:
      - lab_net

    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maximum size of each log file (e.g., 10 megabytes)
        max-file: "3"  # Maximum number of log files to keep
  victim:
    build:
      context: ./victim
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TARGET_URL=http://xss
      - VISIT_INTERVAL=1
    volumes:
    - ./mail_server/docker-data/dms/config/:/mailserver-config/
    #   - ./victim/:/app/
    ports:
      - "127.0.0.1:2780:8080"
    depends_on:
      # - xss
       - csrf
    networks:
      - lab_net
    extra_hosts:
      - "vulnlab.bo:127.0.0.1"
      - "mail.vulnlab.bo:127.0.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maximum size of each log file (e.g., 10 megabytes)
        max-file: "3"  # Maximum number of log files to keep
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.vulnlab.bo
    domainname: vulnlab.bo
    env_file: ./mail_server/mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - mail-data:/var/mail/
      - mail-state:/var/mail-state/
      - mail-logs:/var/log/mail/
      # CORREGIDO: Usa la misma ruta que la web
      - ./mail_server/docker-data/dms/config/:/tmp/docker-mailserver/
    extra_hosts:
      - "vulnlab.bo:127.0.0.1"
      - "mail.vulnlab.bo:127.0.0.1"
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      - lab_net
  correo_web:
    build:
      context: mail_server
      dockerfile: ./Dockerfile
    container_name: mail-web
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=laboratorio_Vuln_cliente
      - ADMIN_USER=admin@vulnlab.bo
      - ADMIN_PASS=admin123
      - MAILSERVER_CONFIG=/mailserver-config/
      - IMAP_HOST=mailserver
      - IMAP_PORT=143
      - SMTP_HOST=mailserver
      - SMTP_PORT=25
    volumes:
      # Usa la misma ruta base
      - ./mail_server/docker-data/dms/config/:/mailserver-config/
    extra_hosts:
      - "vulnlab.bo:127.0.0.1"
      - "mail.vulnlab.bo:127.0.0.1"
    depends_on:
      - mailserver
    restart: always
    networks:
      - lab_net

networks:
  lab_net:
    driver: bridge
volumes:
  mail-data:
  mail-state:
  mail-logs: